### Register a new Parent
POST http://localhost:5000/api/v1/auth/register-parent
Content-Type: application/json

{
  "email": "parent@gmail.com",
  "password": "ParentPassword456&",
  "firstName": "Alice",
  "lastName": "Jones",
  "studentId": 1
}