### Register a new Student User and Student Record
POST http://localhost:5000/api/v1/auth/register-student
Content-Type: application/json

{
"email": "student69.test@example.com",
    "password": "Test226@123",
    "firstName": "John",
    "lastName": "Wick",
    "institutionId":2,
    "gradeLevel": "8"
}

### Register another student (minimal data)
POST http://localhost:5000/api/v1/auth/register-student
Content-Type: application/json

{
  "email": "student.jane.smith@example.com",
  "password": "anotherStudentPass#",
  "firstName": "Jane",
  "lastName": "Smith"
  // institutionId and gradeLevel are optional
}